name: Create Release

on:
  workflow_dispatch:

env:
  APP_NAME: mediadc

jobs:
  build_app:
    runs-on: ubuntu-latest
    name: Build and package app

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Build
        run: make

      - name: Install Krankerl
        run: |
          wget https://github.com/ChristophWurst/krankerl/releases/download/v0.13.0/krankerl_0.13.0_amd64.deb
          sudo dpkg -i krankerl_0.13.0_amd64.deb

      - name: Package app
        run: krankerl package

      - uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: build/artifacts/${{ env.APP_NAME }}.tar.gz
          if-no-files-found: error

  create_release:
    runs-on: ubuntu-latest
    name: Create release draft
    needs: [build_app]

    steps:
      - name: Collect app build
        uses: actions/download-artifact@v2
        with:
          name: tarball
          path: pub_release

      - name: Get release name
        id: get_version
        run: |
          ls -la pub_release
          APP_VERSION=$(sed -n "s/<version>\(.*\)<\/version>/\\1/p" pub_release/appinfo/info.xml)
          echo $APP_VERSION
          echo "::set-output name=version::${APP_VERSION}"
          echo "::set-output tag=v${APP_VERSION}"

      - name: Upload app to release
        uses: ncipollo/release-action@v1.8.8
        with:
          name: ${{ steps.get_version.outputs.version }}
          tag: ${{ steps.get_version.outputs.tag }}
          commit: ${{ github.ref }}
          draft: true
          artifacts: pub_release/*
          token: ${{ secrets.GITHUB_TOKEN }}
