name: Build, Release

on:
  create:
    branches: [main]
    tags:
      - v*

env:
  APP_NAME: mediadc

jobs:
  build_app:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    name: Build and package app

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Build
        run: make

      - name: Install Krankerl
        run: |
          wget https://github.com/ChristophWurst/krankerl/releases/download/v0.13.0/krankerl_0.13.0_amd64.deb
          sudo dpkg -i krankerl_0.13.0_amd64.deb

      - name: Package app
        run: krankerl package

      - uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: build/artifacts/${{ env.APP_NAME }}.tar.gz
          if-no-files-found: error

  create_release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    name: Build and package app
    needs: [build_app]

    steps:
      - name: Collect app build
        uses: actions/download-artifact@v2
        with:
          name: tarball

      - name: Get release name
        id: get_version
        run: |
          echo "::set-output name=version::${GITHUB_REF##refs/tags/v}"

      - name: Upload app to release
        uses: ncipollo/release-action@v1.8.8
        with:
          name: ${{ steps.get_version.outputs.version }}
          draft: true
          artifacts: tarball
          token: ${{ secrets.GITHUB_TOKEN }}
