name: Build

on:
  pull_request:
    branches: [main]
    types: [closed]
    tags:
      - v*
  release:
    types: [created]
  workflow_dispatch:

env:
  APP_NAME: mediadc

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    name: Build and package app

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Build
        run: make

      - name: Install Krankerl
        run: |
          wget https://github.com/ChristophWurst/krankerl/releases/download/v0.13.0/krankerl_0.13.0_amd64.deb
          sudo dpkg -i krankerl_0.13.0_amd64.deb

      - name: Package app
        run: krankerl package

      - uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: build/artifacts/${{ env.APP_NAME }}.tar.gz
          if-no-files-found: error
