name: Generate Binaries-2

on:
  workflow_run:
    workflows: [ Generate Binaries-1 ]
    types:
      - completed

jobs:
  bundler-generate-binaries:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: cloud-py-api/py_bundler/.github/workflows/generate-binaries-2.yml@main
