name: Lint

on:
  pull_request:
    branches: [main, test, dev]
    types: [closed]
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      php_src: ${{ steps.filter.outputs.php_src }}
      js_src: ${{ steps.filter.outputs.js_src }}
      py_src: ${{ steps.filter.outputs.py_src }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          php_src:
            - '**/*.php'
          js_src:
            - '*.js'
            - '**/*.js'
          py_src:
            - 'lib/Service/python/**'
            - 'lib/Service/python/*.py'

  php-linters:
    needs: changes
    if: ${{ needs.changes.outputs.php_src == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [7.4, 8.0]
    name: php ${{ matrix.php-versions }} lint
    steps:
    - uses: actions/checkout@v2

    - name: Setup php${{ matrix.php-versions }}
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        tools: composer:v1
        coverage: none

    - name: Lint
      run: composer run lint

  js-linters:
    needs: changes
    if: ${{ needs.changes.outputs.js_src == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    name: ESLint
    steps:
      - uses: actions/checkout@v2

# https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#installed-software
# do we need this step? this is already installed in github's ubuntu...
      - name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint

  python-linters:
    needs: changes
    if: ${{ needs.changes.outputs.py_src == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    name: PyLint
    steps:
      - uses: actions/checkout@v2

      - name: pylint installation
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: pylint analysis
        run: |
           pylint --rcfile .pylintrc lib/Service/python/*

  psalm-analysis:
    needs: [changes, php-linters]
    if: ${{ needs.changes.outputs.php_src == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    name: Psalm
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions:4.9.3
        with:
          security_analysis: true
          composer_ignore_platform_reqs: false
          report_file: results.sarif

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif

  nextcloud-psalm-analysis:
    needs: [changes, php-linters]
    if: ${{ needs.changes.outputs.php_src == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    strategy:
        matrix:
          ocp-version: [ 'dev-master', 'dev-stable21', 'dev-stable22' ]
    name: Nextcloud ${{ matrix.ocp-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up php
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          tools: composer:v1
          coverage: none

      - name: Install dependencies
        run: composer i

      - name: Install dependencies
        run: composer require --dev christophwurst/nextcloud:${{ matrix.ocp-version }}

      - name: Run coding standards check
        run: composer run psalm

  npm-auidit:
    needs: [changes, js-linters]
    if: ${{ needs.changes.outputs.js_src == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    name: npm-auidit
    steps:
      - uses: actions/checkout@v2

# https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#installed-software
# do we need this step? this is already installed in github's ubuntu...
      - name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x

      - name: Audit
        run: npm audit
