name: Security analysis

on:
  pull_request:
    branches: [main, test, dev]
    types: [closed]
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  psalm:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged != false
    name: Psalm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions:4.9.3
        with:
          security_analysis: true
          composer_ignore_platform_reqs: false
          report_file: results.sarif

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif

  npm:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged != false
    name: npm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x

      - name: Audit
        run: npm audit
