name: Security analysis

on:
  pull_request:
    branches: [main, test, dev]
    types: [closed]
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  psalm:
    runs-on: ubuntu-latest
    name: Psalm
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions:4.9.3
        with:
          security_analysis: true
          composer_ignore_platform_reqs: false
          report_file: results.sarif

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif

  npm:
    runs-on: ubuntu-latest
    name: npm
    steps:
      - uses: actions/checkout@v2

# https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#installed-software
# do we need this step? this is already installed in github's ubuntu...
      - name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x

      - name: Audit
        run: npm audit
