name: Security analysis

on:
  pull_request:
  push:
    branches: [test, dev]
  workflow_dispatch:

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Wait for static-analysis to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Run tests??'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions:4.9.3
        with:
          security_analysis: true
          composer_ignore_platform_reqs: false
          report_file: results.sarif

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif

  npm:
    name: npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x

      - name: Audit
        run: npm audit